// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EthnicGroup struct {
	_tab flatbuffers.Table
}

func GetRootAsEthnicGroup(buf []byte, offset flatbuffers.UOffsetT) *EthnicGroup {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EthnicGroup{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EthnicGroup) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EthnicGroup) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EthnicGroup) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EthnicGroup) Background() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EthnicGroupStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EthnicGroupAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func EthnicGroupAddBackground(builder *flatbuffers.Builder, background flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(background), 0)
}
func EthnicGroupEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
