// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ethnicity struct {
	_tab flatbuffers.Table
}

func GetRootAsEthnicity(buf []byte, offset flatbuffers.UOffsetT) *Ethnicity {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ethnicity{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Ethnicity) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ethnicity) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ethnicity) EthnicGroup(obj *EthnicGroup) *EthnicGroup {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(EthnicGroup)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func EthnicityStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EthnicityAddEthnicGroup(builder *flatbuffers.Builder, ethnicGroup flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ethnicGroup), 0)
}
func EthnicityEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
