// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Hinduism struct {
	_tab flatbuffers.Table
}

func GetRootAsHinduism(buf []byte, offset flatbuffers.UOffsetT) *Hinduism {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Hinduism{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Hinduism) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Hinduism) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Hinduism) Community() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HinduismStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HinduismAddCommunity(builder *flatbuffers.Builder, community flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(community), 0)
}
func HinduismEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
