// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Islam struct {
	_tab flatbuffers.Table
}

func GetRootAsIslam(buf []byte, offset flatbuffers.UOffsetT) *Islam {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Islam{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Islam) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Islam) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Islam) Community() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IslamStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IslamAddCommunity(builder *flatbuffers.Builder, community flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(community), 0)
}
func IslamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
